
CLASS_MAPPING = {
    0: "Ares",
    1: "Astra",
    2: "Breach",
    3: "Brimstone",
    4: "Bucky",
    5: "Buildog",
    6: "Chamber",
    7: "Classic",
    8: "Clove",
    9: "Cypher",
    10: "Deadlock",
    11: "Fade",
    12: "Frenzy",
    13: "Gekko",
    14: "Ghost",
    15: "Guardian",
    16: "Harbor",
    17: "Headshot",
    18: "Iso",
    19: "Jett",
    20: "Judge",
    21: "KAYO",
    22: "Killjoy",
    23: "Marshal",
    24: "Melee",
    25: "Neon",
    26: "Odin",
    27: "Omen",
    28: "Operator",
    29: "Outlaw",
    30: "Phantom",
    31: "Phoenix",
    32: "Raze",
    33: "Reyna",
    34: "Sage",
    35: "Shariff",
    36: "Shorty",
    37: "Skye",
    38: "Sova",
    39: "Spectre",
    40: "Stinger",
    41: "Tejo",
    42: "Vandal",
    43: "Viper",
    44: "Vyse",
    45: "Wallbang",
    46: "Yoru",
    47: "Unknown",
}

# 19+1
WEAPON_CLASSES = [
    "Ares",
    "Bucky",
    "Buildog",
    "Classic",
    "Frenzy",
    "Ghost",
    "Guardian",
    "Judge",
    "Marshal",
    "Melee",
    "Odin",
    "Operator",
    "Outlaw",
    "Phantom",
    "Shariff",
    "Shorty",
    "Spectre",
    "Stinger",
    "Vandal",
    "Unknown",
]

# 26
CHARACTER_CLASSES = [
    "Astra",
    "Breach",
    "Brimstone",
    "Chamber",
    "Clove",
    "Cypher",
    "Deadlock",
    "Fade",
    "Gekko",
    "Harbor",
    "Iso",
    "Jett",
    "KAYO",
    "Killjoy",
    "Neon",
    "Omen",
    "Phoenix",
    "Raze",
    "Reyna",
    "Sage",
    "Skye",
    "Sova",
    "Tejo",
    "Viper",
    "Vyse",
    "Yoru",
]
